version: '3.8'
services:
  app:  &app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "120MB"
  app2:
    <<: *app
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - app2
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "60MB"
volumes:
  postgres_data: